Repository Gisat/deck.gl-geotiff, pull requests merged in 2023-06, with the labels that each got.

#20 Dev
  .github/workflows/release.yml
  .vscode/settings.json
  example/package.json
  example/src/examples/CogBitmapLayerExample.tsx
  geoimage/package-lock.json
  geoimage/package.json
  geoimage/rollup.config.mjs
  geoimage/src/geoimage/geoimage.ts
  geoimage/tsconfig.json
  geoimage/yarn-error.log
  package.json
  tsconfig.json
  yarn.lock
Labels: minor

#21 Dev
  .eslintrc.cjs
  example/src/examples/CogBitmapLayerExample.tsx
  geoimage/package.json
  geoimage/rollup.config.mjs
  geoimage/src/cogbitmaplayer/CogBitmapLayer.ts
  geoimage/src/cogterrainlayer/CogTerrainLayer.ts
  geoimage/src/cogtiles/cogtiles.ts
  geoimage/src/index.ts
  tsconfig.json
  yarn.lock
Labels: minor

#22 remove unused line
  geoimage/src/cogterrainlayer/CogTerrainLayer.ts
Labels: patch

#24 Feature/terrain layer
  geoimage/src/cogterrainlayer/CogTerrainLayer.ts
Labels: minor

#25 Dev
  geoimage/src/cogterrainlayer/CogTerrainLayer.ts
  geoimage/src/geoimage/geoimage.ts
  package-lock.json
  package.json
  yarn.lock
Labels: minor

#27 Feature/terrain layer
  example/src/examples/CogTerrainLayerExample.tsx
  geoimage/CHANGELOG.md
  geoimage/src/cogbitmaplayer/CogBitmapLayer.ts
  geoimage/src/geoimage/geoimage.ts
Labels: minor

#28 Dev
  example/src/examples/CogTerrainLayerExample.tsx
  geoimage/src/cogbitmaplayer/CogBitmapLayer.ts
  geoimage/src/geoimage/geoimage.ts
Labels: minor

#29 Documentation
  README.md
  geoimage/src/cogbitmaplayer/README.md
  geoimage/src/cogterrainlayer/README.md
  geoimage/src/cogtiles/README.md
  geoimage/src/geoimage/README.md
Labels: documentation
